version: '2'

services:
  webserver:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - "5432:5432"
